# Generated by Django 3.1.1 on 2020-09-29 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20200929_0723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='suervey',
        ),
        migrations.AddField(
            model_name='question',
            name='choice',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Choice'),
        ),
        migrations.AddField(
            model_name='surveypage',
            name='question',
            field=models.ManyToManyField(blank=True, null=True, to='polls.Question'),
        ),
    ]
